const menuItems = [
  {
    id: 1,
    name: 'Hamburger',
    price: 3.85,
    calories: 488,
    category: 'Burgers',
  },
  {
    id: 2,
    name: 'Cheeseburger',
    price: 4.25,
    calories: 533,
    category: 'Burgers',
  },
  {
    id: 3,
    name: 'Double Cheeseburger',
    price: 6.55,
    calories: 766,
    category: 'Burgers',
  },
  {
    id: 4,
    name: 'Bacon Cheeseburger',
    price: 5.40,
    calories: 613,
    category: 'Burgers',
  },
  {
    id: 5,
    name: 'Mushroom Swiss Burger',
    price: 5.35,
    calories: 550,
    category: 'Burgers',
  },
  {
    id: 6,
    name: 'Chipotle Bacon Burger',
    price: 5.45,
    calories: 723,
    category: 'Burgers',
  },
  {
    id: 7,
    name: '3 Pc Tender',
    price: 4.55,
    calories: 480,
    category: 'Chicken',
  },
  {
    id: 8,
    name: '5 Pc Tender',
    price: 5.85,
    calories: 800,
    category: 'Chicken',
  },
  {
    id: 9,
    name: 'Breaded Chicken Patty',
    price: 4.75,
    calories: 624,
    category: 'Sandwiches',
  },
  {
    id: 10,
    name: 'Grilled Chicken Breast',
    price: 5.35,
    calories: 550,
    category: 'Sandwiches',
  },
  {
    id: 11,
    name: 'Chicken Bacon Ranch Wrap',
    price: 5.35,
    calories: 624,
    category: 'Sandwiches',
  },
  {
    id: 12,
    name: 'BLT Sandwich',
    price: 5.75,
    calories: 612,
    category: 'Sandwiches',
  },
  {
    id: 13,
    name: 'Vegetarian Garden Patty',
    price: 4.95,
    calories: 330,
    category: 'Sandwiches',
  },
  {
    id: 14,
    name: 'Spicy Chicken Salad',
    price: 6.15,
    calories: 667,
    category: 'Sandwiches',
  },
  {
    id: 15,
    name: 'Chicken Caesar Salad',
    price: 6.35,
    calories: 467,
    category: 'Sandwiches',
  },
  {
    id: 16,
    name: 'Caesar Salad',
    price: 5.15,
    calories: 297,
    category: 'Sandwiches',
  },
  {
    id: 17,
    name: 'French Fries',
    price: 2.15,
    calories: 200,
    category: 'Side Orders',
  },
  {
    id: 18,
    name: 'Onion Rings',
    price: 3.85,
    calories: 370,
    category: 'Side Orders',
  },
  {
    id: 19,
    name: 'Jalapeno Potato Bites',
    price: 3.75,
    calories: 320,
    category: 'Side Orders',
  },
  {
    id: 20,
    name: 'Local Homestead Diary Cheese Curds',
    price: 4.15,
    calories: 680,
    category: 'Side Orders',
  },
  {
    id: 21,
    name: 'Fountain Soda 16 oz.',
    price: 1.55,
    calories: 220,
    category: 'Drinks',
  },
  {
    id: 22,
    name: 'Local Milk',
    price: 2.15,
    calories: 220,
    category: 'Drinks',
  },
  {
    id: 3.95,
    name: 'Naked Juice',
    price: 3.95,
    calories: 220,
    category: 'Drinks',
  },
  {
    id: 1.95,
    name: 'Soy Milk',
    price: 1.95,
    calories: 220,
    category: 'Drinks',
  },
];

export default menuItems;
